baseURL = 'https://jocemarcanabarro.github.io/o-arquivista/'
locale = 'en-us'
title = 'O Arquivista VIP'
theme = "PaperMod"
[markup.goldmark.renderer]
unsafe = true

[params.cover]
    responsiveImages = true
    linkFullImages = true
