baseURL = 'https://www.oarquivista.com/'
languageCode = 'pt-br'
title = 'O Arquivista VIP'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'O Arquivista VIP'
    description = 'O maior acervo multidisciplinar para Laser, 3D, Papercraft e Sublimação.'
    defaultTheme = 'dark'
    showShareButtons = true
    showCodeCopyButtons = true

    # --- CONFIGURAÇÃO DA LOGO NO TOPO ---
    [params.label]
        text = "O Arquivista"
        icon = "images/logo.png"
        iconHeight = 35

    # --- CONFIGURAÇÃO DO ÍCONE DA ABA (FAVICON) ---
    [params.assets]
        favicon = "images/logo.png"
        favicon16x16 = "images/logo.png"
        favicon32x32 = "images/logo.png"
        apple_touch_icon = "images/logo.png"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
    name = 'Grupo Gratuito (Telegram)'
    url = 'https://t.me/O_Arquivista'
    weight = 10
